# Generated by Django 5.0.1 on 2024-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0003_paymentmethodmodel_purchespartynamemdel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchesProductNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
