# Generated by Django 5.0.1 on 2024-01-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0004_purchesproductnamemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchesproductnamemodel',
            name='amount',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='purchesproductnamemodel',
            name='quantity',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
