# Generated by Django 5.0.1 on 2024-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0006_purchescoverbillmodel_purchescoverpartynamemdel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactureProductNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(default=0, max_length=50)),
                ('amount', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
