# Generated by Django 5.0.1 on 2024-01-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0007_manufactureproductnamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactureDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('totalQuantity', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ManufactureProductDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('paper', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('manufacture_expences', models.CharField(max_length=200)),
                ('manufactureDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimondApp.manufacturedetailsmodel')),
            ],
        ),
    ]
