# Generated by Django 5.0.1 on 2024-01-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0013_sellproductbillmodel_sellproductpartynamemdel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellProductProductNameModel',
        ),
        migrations.AddField(
            model_name='sellproductbillmodel',
            name='profit',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AddField(
            model_name='sellproductitemsmodel',
            name='profit',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
