# Generated by Django 5.0.1 on 2024-02-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0014_delete_sellproductproductnamemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstPercentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('GstPercent', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='purchesbillmodel',
            name='gstPercent',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='purchescoverbillmodel',
            name='gstPercent',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='sellproductbillmodel',
            name='gstPercent',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
