# Generated by Django 5.0.1 on 2024-02-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0016_admindetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetailsmodel',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
