# Generated by Django 5.0.1 on 2024-02-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0017_admindetailsmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetailsmodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
