# Generated by Django 5.0.1 on 2024-02-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0019_invoicemodel_invoiceitemsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitemsmodel',
            name='BillDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimondApp.invoicemodel'),
        ),
    ]
