# Generated by Django 5.0.1 on 2024-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0020_alter_invoiceitemsmodel_billdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('heading', models.CharField(max_length=250)),
                ('caption', models.TextField()),
            ],
        ),
    ]
