# Generated by Django 5.0.1 on 2024-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0023_delete_bannerdetailsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('heading', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBackgroundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('heading', models.CharField(max_length=255)),
                ('description_first', models.CharField(max_length=255)),
                ('description_second', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('facebookLink', models.TextField()),
                ('instagramLink', models.TextField()),
                ('linkdinLink', models.TextField()),
                ('twiterLink', models.TextField()),
                ('mapLocationUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('heading', models.CharField(max_length=250)),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('facebookLink', models.TextField()),
                ('instagramLink', models.TextField()),
                ('linkdinLink', models.TextField()),
                ('twiterLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingAreaMdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
