# Generated by Django 5.0.1 on 2024-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0024_bannerdetailsmodel_companybackgroundmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdetailsmodel',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='companybackgroundmodel',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='productdetailsmodel',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='sliderdetailsmodel',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='teammembersmodel',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
