# Generated by Django 5.0.1 on 2024-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0025_alter_bannerdetailsmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofilemodel',
            name='logo',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
