# Generated by Django 5.0.1 on 2024-02-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0026_alter_companyprofilemodel_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerDetailsModel',
        ),
    ]
