# Generated by Django 5.0.1 on 2024-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0027_delete_bannerdetailsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
