# Generated by Django 5.0.1 on 2024-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimondApp', '0028_bannerdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerdetailsmodel',
            name='pageName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
